apiVersion: batch/v1
kind: Job
metadata:
  name: eventify-migrate
  namespace: eventify
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migrate
          image: ghcr.io/joeldragusin/eventify-backend:0.1.0
          command: ["npx", "prisma", "migrate", "deploy"]
          envFrom:
            - secretRef:
                name: eventify-secrets
