apiVersion: v1
kind: Secret
metadata:
    name: eventify-secrets
    namespace: eventify
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:7r8DbC6sGZQ=,iv:mHWkBjhmXKaJBQcjme72UgW0aOnkmIt5a0WQtcpfi1A=,tag:0JdcNy6sdbOQQeC8/2MAWw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:Nvw5hMsRxPo4uPSIl3pJXUDfEczB6NMmDoo1lzFkfSY=,iv:TYUGzPjcQuaqjsT/10Jje8tjTQMS+mndk/AzB2XzytM=,tag:lIN+EmGETle7BWYRfzUzXA==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:VtjHDcmmwew=,iv:AU2xWvsp5qEP+A9x2O3gcgnYnoPo2+PBNYQ6V0HeYaE=,tag:fhOd48shQK0duZ23TWAM5g==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:myxa09lwRlXvE35wZ1tXDpn8FvTynxn/G6JsGzoxSjhHBVrTJF0o6tfDIx+8kA4amP1Q5vB3kML/R6j1zx9PJw==,iv:PDS6sPrEumiHxMxbZv8+PEmp2wBkHIkjsmi2k6ed7Qg=,tag:+nPcBnJgSe4ef0w8CbK+9A==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:19mN37UC5WbciPBnBF6w8NxNqv/AJI6kEkfgXBotAbxQuYrAvpvsIFEIKlFnfzdd+BXNZdaMPmgRwxaZxypo7PGJDhf0M2G2hrZASxA=,iv:6O9GhFMKCTSTz3sXOuYmaDvtL14r3+Vr29UK0UKhE8I=,tag:BZQf92/s42NiivSpi0yrKQ==,type:str]
sops:
    age:
        - recipient: age14kjnjdq5x28r27jvvqktzy94zrs8w8v7tx06640skrdr035clvnsfhxh2e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzd0w5YVA2b05lNzI3UElG
            UFAwcGdEcTU4UHc1YXhRZHpyT2Rta1g3WUc4CnM4Z1dTMmpPZGdEajFndy9sS21U
            YklLNTBlUTIxRkdWK1pxZ3I3ekpLUlEKLS0tIGpjeWZPSzRQc3RwZldDWGJ6K3hr
            cUZKVDhoZUQ5OVNNc3pMMkgydDhiOE0KhJW6HuORRUdrbyXNUChiLVbWwMrqyHH0
            rbxfXo0C3IngA1By0Y4DhIDj4HQm00I+7mMpoqC8QcjOrUBa3g3h7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-11T20:44:07Z"
    mac: ENC[AES256_GCM,data:ImWJRP7cZeB/u639yk4Vef0hPbaxly21DLPXq+erRMw5q1zF4sFVJP0FxEdz1+iNoT8/eYs8t+qibDF88Ea0kpy/5jgOnKoMEkqZeAadDsk7n8aRtrs0MuSk7TlFdbHOBlR4NgVil72Io6r4GYigyoiiK4ehDHTPQKW3vrwpGtc=,iv:DflHzsDqmnm+dUmQuYmhDQsQZK8zThQHo6xPUAkPOXU=,tag:yIREZw33aC/+1/oR9kg+Zw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
